# 4.6 Merging and exporting data

### This script contains the following points:

 1. Create a data to experiment on
 2. Concatenate dataframes
 3. Append data
 4. Merge data

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import os

### 1. Create data to experiment on

In [6]:
# Define a dictionary containing January 2020 data 

data1 = {'customer_id':['6732', '767', '890', '635'], 
        'month':['Jan-20', 'Jan-20', 'Jan-20', 'Jan-20'], 
        'purchased_meat':[0, 13, 3, 4], 
        'purchased_alcohol':[1, 2, 10, 0],
        'purchased_snacks': [10, 5, 1, 7]}

In [8]:
# Define a dictionary containing February 2020 data 

data2 = {'customer_id':['6732', '767', '890', '635'], 
        'month':['Feb-20', 'Feb-20', 'Feb-20', 'Feb-20'], 
        'purchased_meat':[0, 10, 5, 3], 
        'purchased_alcohol':[2, 4, 14, 0],
        'purchased_snacks': [15, 3, 2, 6]}

In [10]:
# Convert the dictionary into DataFrame
df_1 = pd.DataFrame(data1, index=[0, 1, 2, 3])
df_2 = pd.DataFrame(data2, index=[0, 1, 2, 3])

In [12]:
df_1

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Jan-20               0                  1                10
1         767  Jan-20              13                  2                 5
2         890  Jan-20               3                 10                 1
3         635  Jan-20               4                  0                 7

In [14]:
df_2

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Feb-20               0                  2                15
1         767  Feb-20              10                  4                 3
2         890  Feb-20               5                 14                 2
3         635  Feb-20               3                  0                 6

### 2.Concatenate dataframes

In [17]:
# Create a list that contains the dataframes
frames = [df_1, df_2]

In [19]:
# Check output
frames

[  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
 0        6732  Jan-20               0                  1                10
 1         767  Jan-20              13                  2                 5
 2         890  Jan-20               3                 10                 1
 3         635  Jan-20               4                  0                 7,
   customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
 0        6732  Feb-20               0                  2                15
 1         767  Feb-20              10                  4                 3
 2         890  Feb-20               5                 14                 2
 3         635  Feb-20               3                  0                 6]

In [21]:
# Check data types 
type(frames)

list

In [23]:
# Concatenate the dataframes 

df_concat = pd.concat(frames)

In [25]:
# Check output

df_concat

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Jan-20               0                  1                10
1         767  Jan-20              13                  2                 5
2         890  Jan-20               3                 10                 1
3         635  Jan-20               4                  0                 7
0        6732  Feb-20               0                  2                15
1         767  Feb-20              10                  4                 3
2         890  Feb-20               5                 14                 2
3         635  Feb-20               3                  0                 6

In [27]:
# Concatenate the dataframes using axis = 1 (create a wide format as output)

df_concat = pd.concat(frames, axis = 1)

df_concat

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks
0,6732,Jan-20,0,1,10,6732,Feb-20,0,2,15
1,767,Jan-20,13,2,5,767,Feb-20,10,4,3
2,890,Jan-20,3,10,1,890,Feb-20,5,14,2
3,635,Jan-20,4,0,7,635,Feb-20,3,0,6

### 03. Merge data

In [30]:
# Create a new dataframe 
data3 = {'customer_id':['6732', '767', '890', '635'],
    'month':['Jan-20', 'Jan-20', 'Jan-20', 'Jan-20'],
    'days_purchased_on':[0, 10, 4, 1]}

df_3 = pd.DataFrame(data3,index=[0, 1, 2, 3])

In [38]:
# Merge df_1 with df_3
df_merged = df_1.merge(df_3, on = 'customer_id')

df_merged

,customer_id,month_x,purchased_meat,purchased_alcohol,purchased_snacks,month_y,days_purchased_on
0,6732,Jan-20,0,1,10,Jan-20,0
1,767,Jan-20,13,2,5,Jan-20,10
2,890,Jan-20,3,10,1,Jan-20,4
3,635,Jan-20,4,0,7,Jan-20,1

In [40]:
# Another merge
df_merged = df_1.merge(df_3, on = ['customer_id', 'month'])

df_merged

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on
0,6732,Jan-20,0,1,10,0
1,767,Jan-20,13,2,5,10
2,890,Jan-20,3,10,1,4
3,635,Jan-20,4,0,7,1

In [42]:
# Check if costumer_id has same data

df_merged = df_1.merge(df_3, on = ['customer_id', 'month'], indicator = True)

df_merged

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on,_merge
0,6732,Jan-20,0,1,10,0,both
1,767,Jan-20,13,2,5,10,both
2,890,Jan-20,3,10,1,4,both
3,635,Jan-20,4,0,7,1,both

In [44]:
df_merged['_merge'].value_counts()

_merge
both          4
left_only     0
right_only    0
Name: count, dtype: int64

In [53]:
# Append data
df_appended = df_1.append(df_2)

df_appended

AttributeError: 'DataFrame' object has no attribute 'append'

I wanted to try .append() but it is deprecated in padas 2.0.0

### 04. Merging Instacart Data