# Creating a sample for visualizations

In [7]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [9]:
# Import pkl data 
path = '/Users/bobbi/Careerfoundry/InstacartBasketAnalysis_01_25'

sample_data = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared data', 'subset_ords_prods_cust.pkl'))

In [11]:
sample_data.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,product_name,aisle_id,...,ords_flag,gender,state,age,date_joined,n_dependants,fam_status,income,region,max_order
0,2539329,1,1,2,8,NaN,196,1,Soda,77,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
1,2539329,1,1,2,8,NaN,14084,2,Organic Unsweetened Vanilla Almond Milk,91,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
2,2539329,1,1,2,8,NaN,12427,3,Original Beef Jerky,23,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
3,2539329,1,1,2,8,NaN,26088,4,Aged White Cheddar Popcorn,23,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
4,2539329,1,1,2,8,NaN,26405,5,XL Pick-A-Size Paper Towel Rolls,54,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10

In [15]:
# Create sample
np.random.seed(4)

dev = np.random.rand(len(sample_data)) <= 0.7

dev

array([False,  True, False, ...,  True,  True,  True])

In [17]:
# Random sample (70)
big = sample_data[dev]

In [19]:
# Random sample (30)
small = sample_data[~dev]

In [21]:
# Check sample
len(sample_data)

30964564

In [23]:
len(big) + len(small)

30964564

In [25]:
small.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,product_name,aisle_id,...,ords_flag,gender,state,age,date_joined,n_dependants,fam_status,income,region,max_order
0,2539329,1,1,2,8,NaN,196,1,Soda,77,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
2,2539329,1,1,2,8,NaN,12427,3,Original Beef Jerky,23,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
3,2539329,1,1,2,8,NaN,26088,4,Aged White Cheddar Popcorn,23,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
6,2398795,1,2,3,7,15.0,10258,2,Pistachios,117,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10
10,2398795,1,2,3,7,15.0,13032,6,Cinnamon Toast Crunch,121,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,10

In [27]:
# Export small sample
small.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'sample_data.pkl'))