# 01. Import libraries

In [2]:
import pandas as pd
import numpy as np
import os

# 02. Import data

In [5]:
# Import pkl data 
path = '/Users/bobbi/Careerfoundry/InstacartBasketAnalysis_01_25'

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared data', 'ords_prods_grouping_8.pkl'))

In [11]:
customer_data = pd.read_csv(os.path.join(path, '02 Data', 'Original data', 'customers.csv'))

In [13]:
# Check ords_prods data
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,...,prices,_merge,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_ords,ords_flag
0,2539329,1,1,2,8,NaN,196,1,0,both,...,9.0,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2539329,1,1,2,8,NaN,14084,2,0,both,...,12.5,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2539329,1,1,2,8,NaN,12427,3,0,both,...,4.4,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2539329,1,1,2,8,NaN,26088,4,0,both,...,4.7,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,2539329,1,1,2,8,NaN,26405,5,0,both,...,1.0,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

In [15]:
# Check customer data
customer_data.head(10)

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374
5,133128,Cynthia,Noble,Female,Kentucky,43,1/1/2017,2,married,49643
6,152052,Chris,Walton,Male,Montana,20,1/1/2017,0,single,61746
7,168851,Joseph,Hickman,Male,South Carolina,30,1/1/2017,0,single,63712
8,69965,Jeremy,Vang,Male,Texas,47,1/1/2017,1,married,162432
9,82820,Shawn,Chung,Male,Virginia,26,1/1/2017,2,married,32072

# 03. Wrangle data

Based on the data from customers all the columns are important, therefore there is no need to drop any of them.

To follow the same naming as other data columns like 'Surnam', 'STATE' and 'n_dependants' will be modified

In [26]:
# Change column names
customer_data.rename(columns = {'First Name': 'first_name', 'Surnam': 'last_name', 'Gender': 'gender', 'STATE': 'state', 'Age': 'age'}, inplace = True)

In [28]:
customer_data.head()

,user_id,first_name,last_name,gender,state,age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

# 04. Data cleaning

In [31]:
# Data overview
customer_data.describe()

             user_id            age   n_dependants         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

In a quick data overview all the numerical columns seem to be in a reasonalble range. For example the age range is between 18 and 81, or n_dependants column goes from 0 to 3.

Eventhough some outliers are present in columns like age and income, there seems to be no reason to exclude them for now.

In [41]:
# Data validation non-numerical columns
customer_data['gender'].unique()

array(['Female', 'Male'], dtype=object)

There are no misspellings or different methods to refer to gender

In [43]:
customer_data['state'].value_counts()

state
Florida                 4044
Colorado                4044
Illinois                4044
Alabama                 4044
District of Columbia    4044
Hawaii                  4044
Arizona                 4044
Connecticut             4044
California              4044
Indiana                 4044
Arkansas                4044
Alaska                  4044
Delaware                4044
Iowa                    4044
Idaho                   4044
Georgia                 4044
Wyoming                 4043
Mississippi             4043
Oklahoma                4043
Utah                    4043
New Hampshire           4043
Kentucky                4043
Maryland                4043
Rhode Island            4043
Massachusetts           4043
Michigan                4043
New Jersey              4043
Kansas                  4043
South Dakota            4043
Minnesota               4043
Tennessee               4043
New York                4043
Washington              4043
Louisiana               4043
Montana                 4043
North Dakota            4043
Wisconsin               4043
Nebraska                4043
Vermont                 4043
Nevada                  4043
Maine                   4043
North Carolina          4043
West Virginia           4043
Virginia                4043
Oregon                  4043
New Mexico              4043
Texas                   4043
Pennsylvania            4043
Ohio                    4043
South Carolina          4043
Missouri                4043
Name: count, dtype: int64

In [46]:
customer_data['state'].value_counts().unique()

array([4044, 4043])

Also in state doesn't seem to be any misspelling and all the states follow the same naming convention. There are 50 states plus Distict of Columbia

In [49]:
customer_data['fam_status'].unique()

array(['married', 'single', 'living with parents and siblings',
       'divorced/widowed'], dtype=object)

All family status follow the same convention and there are no misspellings

### Mixed data types

In [38]:
# Check data types
customer_data.dtypes

user_id          int64
first_name      object
last_name       object
gender          object
state           object
age              int64
date_joined     object
n_dependants     int64
fam_status      object
income           int64
dtype: object

In [63]:
# Checking mixed types
for col in customer_data.columns.tolist():
  weird = (customer_data[[col]].map(type) != customer_data[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (customer_data[weird]) > 0:
    print (col)

In [54]:
# Use .map() to identify data types
data_types = customer_data['first_name'].map(type).value_counts()

In [56]:
data_types

first_name
<class 'str'>      194950
<class 'float'>     11259
Name: count, dtype: int64

In [58]:
# Replace 'float' data types with 'str'

customer_data['first_name'] = customer_data['first_name'].astype('str')

In [60]:
customer_data['first_name'].map(type).value_counts()

first_name
<class 'str'>    206209
Name: count, dtype: int64

After checking every column for mixed data types the results showed that 'firs_name' was of string and float data type. As this column stores non-numerical data, names, I changed the data type of the column to string.

### Duplicates

In [71]:
#Check for duplicates
duplicates = customer_data[customer_data.duplicated()]

duplicates

Empty DataFrame
Columns: [user_id, first_name, last_name, gender, state, age, date_joined, n_dependants, fam_status, income]
Index: []

The analysis shows that there are no duplicates

### Missing data

In [75]:
# Finding missing data
customer_data.isnull().sum()

user_id         0
first_name      0
last_name       0
gender          0
state           0
age             0
date_joined     0
n_dependants    0
fam_status      0
income          0
dtype: int64

The analysis shows that there is no missing data

### Export clean customer data

In [110]:
customer_data.to_pickle(os.path.join(path, '02 Data', 'Prepared data', 'customer_data.pkl'))

# 05. Combine customer data with prepared data

In [79]:
# Check data types
ords_prods_merge.dtypes

order_id                    int64
user_id                     int64
order_number                int64
orders_day_of_week          int64
order_hour_of_day           int64
days_since_last_order     float64
product_id                  int64
add_to_cart_order           int64
reordered                   int64
existing_merge           category
product_name               object
aisle_id                    int64
department_id               int64
prices                    float64
_merge                   category
busiest_days               object
busiest_period_of_day      object
max_order                   int64
loyalty_flag               object
mean_price                float64
spending_flag              object
median_ords               float64
ords_flag                  object
dtype: object

In [81]:
customer_data.shape

(206209, 10)

In [85]:
# First I am going to drop the previous '_merge' columns 
ords_prods_merge.drop(columns=['existing_merge', '_merge'], inplace=True)

In [87]:
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_ords,ords_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,7,9.0,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,16,12.5,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,19,4.4,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,19,4.7,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,17,1.0,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

In [89]:
# Merge both dataframes
ords_prods_customer = ords_prods_merge.merge(customer_data, on='user_id', how='inner', indicator=True)

In [91]:
# Check merge results
ords_prods_customer['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [93]:
ords_prods_customer.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,first_name,last_name,gender,state,age,date_joined,n_dependants,fam_status,income,_merge
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both

In [95]:
ords_prods_customer.shape

(32404859, 31)

Due to the size of the dataframe, I have decided that there are some columns that are not needed to have a complete dataframe. I will drop the following columns:
* 'max_order': It was used to classify user loyalty
* 'mean_price': Used to classify user spending habits
* 'median_ords': Used to classify order frequency
* '_merge': Used to get information about the dataframes merge

In [100]:
ords_prods_customer.drop(columns=['max_order', 'mean_price', 'median_ords', '_merge'], inplace=True)

In [102]:
ords_prods_customer.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,ords_flag,first_name,last_name,gender,state,age,date_joined,n_dependants,fam_status,income
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423

In [104]:
ords_prods_customer.shape

(32404859, 27)

# 06. Export data

In [107]:
# Export data in pickle
ords_prods_customer.to_pickle(os.path.join(path, '02 Data', 'Prepared data', 'ords_prods_customer.pkl'))