# 01. Import libraries

In [2]:
import pandas as pd
import numpy as np
import os

# 02. Import data

In [4]:
# Import pkl data 
path = '/Users/bobbi/Careerfoundry/InstacartBasketAnalysis_01_25'

ords_prods_merge = df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared data', 'ords_prods_busy_day_hour_7.pkl'))

ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Average orders

In [5]:
df = ords_prods_merge[:1000000]

In [6]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Average orders

In [7]:
df.shape

(1000000, 17)

# 03. Grouping data

In [9]:
df.groupby('product_name')

.groupby() splits the data into groups based on some criteria. 

After it nedds to be aggragated and combine into a dataframe or other data structure.

### Aggregating Data with agg()

In [12]:
# Simple aggregation
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

df.groupby('department_id')['order_number'].mean()

In [14]:
# Perform multiple aggreagations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                14.800024   1  99
2                17.091743   1  98
3                17.913544   1  99
4                17.893092   1  99
5                15.214270   1  99
6                15.382135   1  99
7                17.694027   1  99
8                16.458105   1  91
9                15.957363   1  99
10               20.091818   1  99
11               16.482026   1  99
12               15.615061   1  99
13               16.484023   1  99
14               17.524632   1  99
15               15.691875   1  99
16               18.014071   1  99
17               16.150593   1  99
18               19.602850   1  99
19               17.631340   1  99
20               17.138607   1  99
21               21.956893   1  97

### Aggregating Data with transform()

In [16]:
# Create a loyality flag column
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/bs/25x482152nx68y1wp8l2g42c0000gn/T/ipykernel_6419/2384578368.py:2: FutureWarning: The provided callable <function max at 0x1117780e0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [17]:
ords_prods_merge.head(15)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Average orders,10
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Average orders,10
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Average orders,10
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Average orders,10
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Average orders,10
5,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,both,Least busy days,Average orders,10
6,2398795,1,2,3,7,15.0,10258,2,0,both,Pistachios,117,19,3.0,both,Least busy days,Average orders,10
7,2398795,1,2,3,7,15.0,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,Least busy days,Average orders,10
8,2398795,1,2,3,7,15.0,13176,4,0,both,Bag of Organic Bananas,24,4,10.3,both,Least busy days,Average orders,10
9,2398795,1,2,3,7,15.0,26088,5,1,both,Aged White Cheddar Popcorn,23,19,4.7,both,Least busy days,Average orders,10
10,2398795,1,2,3,7,15.0,13032,6,0,both,Cinnamon Toast Crunch,121,14,4.0,both,Least busy days,Average orders,10
11,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,both,Least busy days,Most orders,10
12,473747,1,3,3,12,21.0,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,Least busy days,Most orders,10
13,473747,1,3,3,12,21.0,10258,3,1,both,Pistachios,117,19,3.0,both,Least busy days,Most orders,10
14,473747,1,3,3,12,21.0,25133,4,0,both,Organic String Cheese,21,16,8.6,both,Least busy days,Most orders,10

In [18]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Average orders,10
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Average orders,10
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Average orders,10
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Average orders,10
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Average orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,738281,2,4,2,10,8.0,21150,13,0,both,Fire Grilled Steak Bowl,38,1,5.9,both,Regularly busy,Most orders,14
96,1673511,2,5,3,11,8.0,47144,1,0,both,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,both,Least busy days,Most orders,14
97,1673511,2,5,3,11,8.0,5322,2,0,both,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,both,Least busy days,Most orders,14
98,1673511,2,5,3,11,8.0,17224,3,0,both,Oats & Honey Gluten Free Granola,3,19,1.6,both,Least busy days,Most orders,14
99,1673511,2,5,3,11,8.0,38656,4,0,both,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,both,Least busy days,Most orders,14

In [19]:
pd.options.display.max_rows = None

### Deriving Columns with loc()

In [21]:
# Create a flat that assigns a "loyalty" label to a user
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [22]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [23]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [24]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [95]:
ords_prods_merge.groupby('loyalty_flag')['user_id'].nunique()

loyalty_flag
Loyal customer       17017
New customer        112328
Regular customer     76864
Name: user_id, dtype: int64

In [26]:
# Check specific columns 
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head()

   user_id  loyalty_flag  order_number
0        1  New customer             1
1        1  New customer             1
2        1  New customer             1
3        1  New customer             1
4        1  New customer             1

In [27]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1

# 04. Exercise

### Find the aggregated mean for the entire dataframe

In [30]:
ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

The mean is higher when using the whole dataframe. This is normal as the whole dataframe has more data than the subset that only represents 1000000 values.

### Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category

In [33]:
# Create statistics for each loyalty flag

loyalty_price_stats = ords_prods_merge.groupby(['loyalty_flag'])['prices'].describe()

print(loyalty_price_stats)

                       count      mean       std  min  25%  50%   75%   max
loyalty_flag
Loyal customer    10284093.0  7.773783  4.205919  1.0  4.2  7.4  11.2  25.0
New customer       6243990.0  7.801494  4.266494  1.0  4.2  7.4  11.3  25.0
Regular customer  15876776.0  7.798524  4.254579  1.0  4.2  7.4  11.3  25.0

The data does not show meaningful differences in spending habits or product preferences based on loyalty status. The differences in means and quartiles are too small to draw strong conclusions.

Since product price preferences are very similar, loyalty programs might not need to focus on altering pricing strategies significantly.

### Target different types of spenders in their marketing campaigns.

Create a spending flag for each user based on the average price across all their orders using the following criteria:
* If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
* If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [37]:
# Calculate the mean price per user
user_mean_prices = ords_prods_merge.groupby('user_id')['prices'].mean()

In [38]:
# Create column 'mean_price' by mapping user_mean_prices to each user_id

ords_prods_merge['mean_price'] = ords_prods_merge['user_id'].map(user_mean_prices)

In [39]:
# Assign spending flags

ords_prods_merge.loc[ords_prods_merge['mean_price'] < 10, 'spending_flag'] = 'Low spender'
ords_prods_merge.loc[ords_prods_merge['mean_price'] >= 10, 'spending_flag'] = 'High spender'

In [40]:
ords_prods_merge[['user_id', 'mean_price', 'spending_flag']].head(15)

    user_id  mean_price spending_flag
0         1    6.367797   Low spender
1         1    6.367797   Low spender
2         1    6.367797   Low spender
3         1    6.367797   Low spender
4         1    6.367797   Low spender
5         1    6.367797   Low spender
6         1    6.367797   Low spender
7         1    6.367797   Low spender
8         1    6.367797   Low spender
9         1    6.367797   Low spender
10        1    6.367797   Low spender
11        1    6.367797   Low spender
12        1    6.367797   Low spender
13        1    6.367797   Low spender
14        1    6.367797   Low spender

In [41]:
# Print unique users
ords_prods_merge[['user_id', 'mean_price', 'spending_flag']].drop_duplicates(subset='user_id').head(15)

      user_id  mean_price spending_flag
0           1    6.367797   Low spender
59          2    7.515897   Low spender
254         3    8.197727   Low spender
342         4    8.205556   Low spender
360         5    9.189189   Low spender
397         6    8.471429   Low spender
411         7    7.466990   Low spender
617         8    8.781633   Low spender
666         9    7.607895   Low spender
742        10    8.651049   Low spender
885        11    8.328723   Low spender
979        12    8.116216   Low spender
1053       13    8.708642   Low spender
1134       14    8.014286   Low spender
1344       15    3.980556   Low spender

In [42]:
ords_prods_merge['spending_flag'].value_counts()

spending_flag
Low spender     32285150
High spender      119709
Name: count, dtype: int64

### Create an order frequency flag that marks the regularity of a user’s ordering behavior

The criteria for the flag should be as follows:
* If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
* If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
* If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [45]:
# Calculate the median price per user
user_median_ords = ords_prods_merge.groupby('user_id')['days_since_last_order'].median()

In [46]:
# Create column 'median_ords' by mapping user_mean_prices to each user_id
ords_prods_merge['median_ords'] = ords_prods_merge['user_id'].map(user_median_ords)

In [47]:
# Assign order frequency flags
ords_prods_merge.loc[ords_prods_merge['median_ords'] <= 10, 'ords_flag'] = 'Frequent customer'
ords_prods_merge.loc[(ords_prods_merge['median_ords'] > 10) & (ords_prods_merge['median_ords'] <= 20), 'ords_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['median_ords'] > 20, 'ords_flag'] = 'Non-frequent customer'

In [48]:
ords_prods_merge[['user_id', 'median_ords', 'ords_flag']].drop_duplicates(subset='user_id').head(15)

      user_id  median_ords              ords_flag
0           1         20.5  Non-frequent customer
59          2         13.0       Regular customer
254         3         10.0      Frequent customer
342         4         20.0       Regular customer
360         5         11.0       Regular customer
397         6          6.0      Frequent customer
411         7          9.0      Frequent customer
617         8         30.0  Non-frequent customer
666         9         30.0  Non-frequent customer
742        10         23.0  Non-frequent customer
885        11         14.0       Regular customer
979        12         30.0  Non-frequent customer
1053       13          7.0      Frequent customer
1134       14         30.0  Non-frequent customer
1344       15         10.0      Frequent customer

In [49]:
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,...,prices,_merge,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_ords,ords_flag
0,2539329,1,1,2,8,NaN,196,1,0,both,...,9.0,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2539329,1,1,2,8,NaN,14084,2,0,both,...,12.5,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2539329,1,1,2,8,NaN,12427,3,0,both,...,4.4,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2539329,1,1,2,8,NaN,26088,4,0,both,...,4.7,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,2539329,1,1,2,8,NaN,26405,5,0,both,...,1.0,both,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

### Exercise Correction

In [51]:
ords_prods_merge['ords_flag'].value_counts()

ords_flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
Name: count, dtype: int64

In [52]:
ords_prods_merge.groupby('ords_flag')['user_id'].nunique()

ords_flag
Frequent customer        86596
Non-frequent customer    59619
Regular customer         59993
Name: user_id, dtype: int64

# 04. Exporting data

In [54]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_grouping_8.pkl'))