# 01. Import libraries¶

In [6]:
# Import libraries 
import pandas as pd
import numpy as np
import os

# 02. Import data

In [9]:
# Import products.csv
df_prod = pd.read_csv(r'/Users/bobbi/Careerfoundry/InstacartBasketAnalysis_01_25/02 Data/Original data/products.csv', 
                 index_col=False)

In [11]:
# Import orders.csv
df_orders = pd.read_csv(r'/Users/bobbi/Careerfoundry/InstacartBasketAnalysis_01_25/02 Data/Original data/orders.csv', 
                 index_col=False)

In [13]:
# Import departments.csv
path = '/Users/bobbi/Careerfoundry/InstacartBasketAnalysis_01_25'
df_dep = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'departments.csv'), index_col = False)

# 03. Data wrangling procedure

## Drop columns

In [17]:
df_orders.drop(columns = ['eval_set'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [19]:
df_ords = df_orders.drop(columns = ['eval_set'])

In [21]:
df_ords['days_since_prior_order'].value_counts(dropna = False)

days_since_prior_order
30.0    369323
7.0     320608
6.0     240013
4.0     221696
3.0     217005
5.0     214503
NaN     206209
2.0     193206
8.0     181717
1.0     145247
9.0     118188
14.0    100230
10.0     95186
13.0     83214
11.0     80970
12.0     76146
0.0      67755
15.0     66579
16.0     46941
21.0     45470
17.0     39245
20.0     38527
18.0     35881
19.0     34384
22.0     32012
28.0     26777
23.0     23885
27.0     22013
24.0     20712
25.0     19234
29.0     19191
26.0     19016
Name: count, dtype: int64

## Rename columns

In [24]:
df_ords.rename(columns = {'order_dow' : 'orders_day_of_week'}, inplace = True)
df_ords.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

## Changing data types

In [27]:
df_ords['order_id'] = df_ords['order_id'].astype('str')
df_ords['order_id'].dtypes

dtype('O')

## Transposing data

In [30]:
# Transposing df_dep
df_dep_t = df_dep.T
df_dep_t

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [32]:
# Changing header
df_dep_t.reset_index()

new_header = df_dep_t.iloc[0]

df_dep_t_new = df_dep_t[1:]

df_dep_t_new.columns = new_header

df_dep_t_new

department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

# 04. Data dictionaries

In [35]:
# Create data dictionary
data_dict = df_dep_t_new.to_dict('index')
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [37]:
df_prods = df_prod
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [39]:
print(data_dict.get('19'))

{'department': 'snacks'}

In [41]:
# Subsetting
df_snacks =  df_prods[df_prods['department_id']==19]
df_snacks

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5
...,...,...,...,...,...
49666,49662,Bacon Cheddar Pretzel Pieces,107,19,3.6
49669,49665,Super Dark Coconut Ash & Banana Chocolate Bar,45,19,6.9
49670,49666,Ginger Snaps Snacking Cookies,61,19,5.2
49675,49671,Milk Chocolate Drops,45,19,3.0
49683,49679,Famous Chocolate Wafers,61,19,6.0

# 05. Exercises

### Find another identifier variable in the df_ords dataframe that doesn’t need to be included in your analysis as a numeric variable and change it to a suitable format.

In [45]:
df_ords.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In the data frame order_id is enough to identify the order so I don't think that order_number is needed (I misunderstood the exercise and I thought I had to drop another column instead of changing the data type)

In [48]:
df_ords = df_ords.drop(columns = ['order_number'])
df_ords.head()

,order_id,user_id,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,2,8,NaN
1,2398795,1,3,7,15.0
2,473747,1,3,12,21.0
3,2254736,1,4,7,29.0
4,431534,1,4,15,28.0

Changing data type in df_orders

In [51]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [53]:
df_orders['order_number'] = df_orders['order_number'].astype('str')
df_orders.describe()  #check if order_number is still numerical

,order_id,user_id,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,6.000000e+00,2.300000e+01,3.000000e+01

### Look for a variable in your df_ords dataframe with an unintuitive name and change its name without overwriting the dataframe.

In [56]:
df_ords.rename(columns = {'days_since_prior_order' : 'days_since_last_order'}, inplace = True)
df_ords.head()

,order_id,user_id,orders_day_of_week,order_hour_of_day,days_since_last_order
0,2539329,1,2,8,NaN
1,2398795,1,3,7,15.0
2,473747,1,3,12,21.0
3,2254736,1,4,7,29.0
4,431534,1,4,15,28.0

 ### Your client wants to know what the busiest hour is for placing orders.

In [59]:
df_ords['order_hour_of_day'].value_counts(dropna = False)

order_hour_of_day
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
8     178201
19    140569
20    104292
7      91868
21     78109
22     61468
23     40043
6      30529
0      22758
1      12398
5       9569
2       7539
4       5527
3       5474
Name: count, dtype: int64

The busiest time of the day is between 9:00 and 16:00, with 10:00 as peak order hour

As df_ords['order_hour_of_day'] is not affected by the mistake in the first exercise I kept it like this and now I am going to overwrite df_ords with the propers dataframe of df_orders

In [63]:
df_ords = df_orders
df_ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

I dropped again eval_set to leave the dataframe as it should be (sorry for all the confusion)

In [70]:
df_ords.drop(columns = ['eval_set'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [72]:
df_ords.rename(columns = {'days_since_prior_order' : 'days_since_last_order'}, inplace = True)
df_ords.head() #Fixed the column naming too

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_last_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

### Determine the meaning behind a value of 4 in the "department_id" column within the df_prods dataframe using a data dictionary.

In [75]:
print(data_dict.get('4'))

{'department': 'produce'}

### The sales team in your client’s organization wants to know more about breakfast item sales.

In [78]:
df_breakfast = df_prods[df_prods['department_id']==14]

In [80]:
df_breakfast.head()

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6

### Details about products that customers might use to throw dinner parties. Your task is to find all observations from the entire dataframe that include items from the following departments: alcohol, deli, beverages, and meat/seafood.

In [83]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [85]:
df_dinner_parties = df_prods.loc[df_prods['department_id'].isin([5, 7, 12, 20])]
df_dinner_parties

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1
...,...,...,...,...,...
49676,49672,Cafe Mocha K-Cup Packs,26,7,6.5
49679,49675,Cinnamon Dolce Keurig Brewed K Cups,26,7,14.0
49680,49676,Ultra Red Energy Drink,64,7,14.5
49686,49682,California Limeade,98,7,4.3
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3

In [87]:
# Counts of rows and columns in new dataframe
df_dinner_parties.shape

(7650, 5)

### Inspect user 1

In [90]:
df_user_1 = df_ords[df_ords['user_id'] == 1]
df_user_1

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_last_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0

In [92]:
# Basic stats for user_1
df_user_1.describe()

,order_id,user_id,order_dow,order_hour_of_day,days_since_last_order
count,1.100000e+01,11.0,11.000000,11.000000,10.000000
mean,1.923450e+06,1.0,2.636364,10.090909,19.000000
std,1.071950e+06,0.0,1.286291,3.477198,9.030811
min,4.315340e+05,1.0,1.000000,7.000000,0.000000
25%,8.690170e+05,1.0,1.500000,7.500000,14.250000
50%,2.295261e+06,1.0,3.000000,8.000000,19.500000
75%,2.544846e+06,1.0,4.000000,13.000000,26.250000
max,3.367565e+06,1.0,4.000000,16.000000,30.000000

## Export data

In [95]:
# Export wrangled orders data
df_ords.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv'))

In [96]:
# Export wrangled departments data
df_dep_t_new.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'departments_wrangled.csv'))

In [99]:
df_ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_last_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [101]:
df_ords.rename(columns = {'days_since_prior_order' : 'days_since_last_order'}, inplace = True)
df_ords.head() #Fixed the column naming too

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_last_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [103]:
df_ords = df_orders.drop(columns = ['eval_set'])
df_ords.rename(columns = {'order_dow' : 'orders_day_of_week'}, inplace = True)
df_ords.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [105]:
# Export wrangled orders data
df_ords.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv'))